# Generated by Django 5.2.4 on 2025-07-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster_url', models.URLField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
